export const randomFeelings = {
  Positive: [
    "Awesome ! 😄",
    "That's great ! ✨",
    "Yay ! 😊",
    "Feeling good ! 🎉",
    "Keep shining ! ☀️",
    "So happy ! 😍",
    "All smiles ! 😁",
    "Fantastic ! 🌟",
    "Full of joy ! 🎈",
    "Loving it ! ❤️",
  ],
  Neutral: [
    "Meh.. 😐",
    "Quite balanced 🤔",
    "Nothing special today",
    "Just okay 😶",
    "Taking it easy 🛋️",
    "Calm and steady 🧘",
    "Neutral vibes 😌",
    "No strong feelings",
    "In between ⚖️",
    "Going with the flow 🌊",
  ],
  Negative: [
    "Oh no... 😢",
    "Chin up ! 💪",
    "Better days will come 🌧️→☀️",
    "Feeling down 😞",
    "Stay strong ! ✊",
    "Not the best day. 😔",
    "Keep fighting ! 🥊",
    "Hang in there ! 🧗",
    "It's okay to cry 😭",
    "This too shall pass ⏳",
  ],
};
