export const randomFeelings = {
  Positive: [
    "Awesome ! 😄",
    "That's great ! ✨",
    "Yay ! 😊",
    "Feeling good ! 🎉",
    "Keep shining ! ☀️",
    "So happy ! 😍",
    "All smiles ! 😁",
    "Fantastic ! 🌟",
    "Full of joy ! 🎈",
    "Loving it ! ❤️",
    "Life is beautiful ! 🌸",
    "On top of the world ! 🏔️",
    "Can't stop smiling ! 😃",
    "Pure happiness ! 🥰",
    "Everything's going right ! 🍀",
    "Way to go ! 🏆",
    "Go you ! 🚀",
    "You rock ! 🤘",
    "Keep smiling ! 😁",
    "Love this ! ❤️",
    "You glow ! 🌟",
  ],
  Neutral: [
    "Meh... 😐",
    "Quite balanced 🤔",
    "Nothing special today.",
    "Just okay 😶",
    "Taking it easy 🛋️",
    "Calm and steady 🧘",
    "Neutral vibes 😌",
    "No strong feelings",
    "In between ⚖️",
    "Going with the flow 🌊",
    "Same old, same old 🕰️",
    "Neither here nor there 🚶",
    "Just another day 📅",
    "So-so 🤷",
    "Average mood today 📊",
    "As usual 📅",
    "Taking it slow 🐢",
    "No rush 🕰️",
  ],
  Negative: [
    "Oh no... 😢",
    "Chin up ! 💪",
    "Better days will come 🌧️→☀️",
    "Feeling down 😞",
    "Stay strong ! ✊",
    "Not the best day 😔",
    "Keep fighting ! 🥊",
    "Hang in there ! 🧗",
    "It's okay to cry 😭",
    "This too shall pass ⏳",
    "Feeling blue 💙",
    "A bit lost right now 🧭",
    "Tough times 🥀",
    "Need a hug 🤗",
    "Trying to hold on 🪢",
    "Don’t worry 🤍",
    "Keep going 🏃",
    "You’ll heal 🩹",
    "Hang tight 🪢",
  ],
};
